### ISSUE TITLE
Goal of OpenJSSE

### ISSUE THREAD

**Issue by yschimke** [openjsse/openjsse#23]
> OpenJSSE: A JSSE provider that supports TLS 1.3 on Java SE 8.

Since this is now backported anyway, is the goal of the project to bring latest changes from JDK 11 or the LTS?

**Comment by alexeybakhtin** [comment]
This is LTS for those who still use it. Also, it is slightly different from Java SE 8 TLSv1.3 implementation: more cipher suites, different default configuration
