### ISSUE TITLE
Preferred way to activate OpenJSSE

### ISSUE THREAD

**Issue by yschimke** [openjsse/openjsse#5]
Your example assumes that OpenJSSE is already installed as the priority provider for SSL etc.  It seems on your own VMs, you'll have a command line option to enable (-XX:+UseOpenJSSE) or maybe make it the default.

But what's the advice for OpenJDK users?

1) edit the java.security config file?
2) Register with Security.insertProviderAt
3) Direct usage of org.openjsse.sun.security.ssl.SSLSocketFactoryImpl

3 seems the most likely because you may need to configure ALPN etc.

**Comment by yschimke** [comment]
FYI OkHttp PR with support for HTTP/2 (via ALPN) and TLSv1.3

https://github.com/square/okhttp/pull/5369/files

**Comment by alexeybakhtin** [comment]
Hello Yuri,

OpenJSSE for OpenJDK can be installed in two possible ways:
1) add OpenJSSE provider in the list of security providers of java.security file
2) registered at runtime with Security.insertProviderAt method

However you'll better use Azul JDK8 builds as soon as it has preintegrated and fully tested support for OpenJSSE provider with -XX:+UseOpenJSSE

**Comment by yschimke** [comment]
Does UseOpenJSSE flag put it first? That would mean that okhttp will work automatically with TLS 1.3 and HTTP/2 in Azul JDK.

**Comment by alexeybakhtin** [comment]
Right, -XX:+UseOpenJSSE flag makes OpenJSSE default TLS provider in Azul JDK. So, all applications able to connect with TLSv1.3 automatically without additional configuration and code changes.
